---
- name: nginx install & start services
  hosts: webservers
  become: true

  tasks:
  - name: install nginx
    yum:
     name: nginx
     state: latest

  - name: start nginx
    service:
      name: nginx
      state: started

- hosts: webservers
  tasks:
    - name: Install PHP
      become: true
      apt:
        name: php
        state: latest

- hosts: webservers
  tasks:
    - name: Install PHP-FPM
      become: true
      apt:
        name: php-fpm
        state: latest

- hosts: webservers
  tasks:
  - name: Create php file
    file:
      path: "/var/www/html/index.php"
      state: touch
      content: <?php echo date("Y-m-d H:i:s") . " Welcome to " . gethostname() . "|" .$_SERVER['SERVER_ADDR'] .":" . $_SERVER['SERVER_PORT'] ."<br>\n"; ?> 

- hosts: webservers
  tasks:
  - name: delete old nginx config file
    file:
      path: /etc/nginx/sites-available/default.conf
      state: absent

- hosts: haproxy
  tasks:
    - name: install haproxy
      apt: name=haproxy state=present
