---
- name: nginx install & start services
  hosts: webservers
  become: true

  tasks:
  - name: install nginx
    yum:
     name: nginx
     state: latest

  - name: start nginx
    service:
      name: nginx
      state: started


- hosts: haproxy
  tasks:
    - name: install haproxy
      apt: name=haproxy state=present


- hosts: webservers
  tasks:
    - name: Install PHP
      become: true
      apt:
        name: php
        state: latest

- hosts: webservers
  tasks:
    - name: Install PHP-FPM
      become: true
      apt:
        name: php-fpm
        state: latest
